pipeline {
    agent {
        docker {
            image 'python:3'
            args '-u root'
        }
    }

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('checkout') {
        steps {
            git credentialsId: '4a313cc0-0775-4139-83df-05384f27d375',
            url: 'https://github.com/gowri9493/Jenkins-Zero-To-Hero',
            branch: 'main'
        }
    }
}
    post {
        echo "pipeline success"
    }
        
}
