pipeline {
    agent any


    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('checkout') {
        steps {
            git credentialsId: '4a313cc0-0775-4139-83df-05384f27d375',
            url: 'https://github.com/gowri9493/Jenkins-Zero-To-Hero',
            branch: 'main'
        }
    }
        stage('Build Docker') {
            steps {
                 script {
                    sh '''
                    echo 'Build Docker Image'
                    docker build -t gowri9493/cicd-e2e:${BUILD_NUMBER} . -f python-jenkins-argocd-k8s
                    '''
                }
            }
        }
}
    
        
}

